// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvoQ3S4dlQsLMp96RLXv9TJIhC8y5gfEY',
    appId: '1:915509909329:web:470baa5dfdcb6d95512570',
    messagingSenderId: '915509909329',
    projectId: 'palette-app1',
    authDomain: 'palette-app1.firebaseapp.com',
    storageBucket: 'palette-app1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp5dVW-yE3xLQDxitN9Jqxu5Jek4kUF_4',
    appId: '1:915509909329:android:5224c60a67bbf404512570',
    messagingSenderId: '915509909329',
    projectId: 'palette-app1',
    storageBucket: 'palette-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj3kDwQ3x6P2vITWQblhR4d9eWf5eQOh0',
    appId: '1:915509909329:ios:27bdbfda99586dca512570',
    messagingSenderId: '915509909329',
    projectId: 'palette-app1',
    storageBucket: 'palette-app1.firebasestorage.app',
    iosBundleId: 'com.example.projectPallete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj3kDwQ3x6P2vITWQblhR4d9eWf5eQOh0',
    appId: '1:915509909329:ios:27bdbfda99586dca512570',
    messagingSenderId: '915509909329',
    projectId: 'palette-app1',
    storageBucket: 'palette-app1.firebasestorage.app',
    iosBundleId: 'com.example.projectPallete',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvoQ3S4dlQsLMp96RLXv9TJIhC8y5gfEY',
    appId: '1:915509909329:web:5d1aee833933b05d512570',
    messagingSenderId: '915509909329',
    projectId: 'palette-app1',
    authDomain: 'palette-app1.firebaseapp.com',
    storageBucket: 'palette-app1.firebasestorage.app',
  );

}